### PR TITLE
requirements + data

### PR DESCRIPTION
**Pull request by ltetrel**
moving software requirement to right place
update data requirement
update notebook with repo2data

### CODE REVIEW

**Comment by ltetrel** [comment]
conflict due to old requirement file (at the source of repo) that can be safely deleted

**Review by htwangtw — COMMENTED** [review]
I would still keep the requirement file for building the book separately. That's why there was `content/requirements.txt` 
Or we can change in the build from this:
https://github.com/main-educational/intro_ML/blob/903116fc0249c2c517e27343f570c9729bca4e52/.github/workflows/book.yml#L22-L24

To:
```
    - name: Install dependencies
      run: |
        pip install -r binder/requirements.txt
        pip install jupyter-book
```

**Comment by ltetrel** [comment]
Also the plan was to push that to NeuroLibre at one point).
If that is still the case then putting in the requirements in the binder folder is the standard (for any binder environment).

**Comment by htwangtw** [comment]
> Also the plan was to push that to NeuroLibre at one point. If that is still the case then putting in the requirements in the binder folder is the standard (for any binder environment) and mandatory for Neurolibre.

Fair point. Since the workshop is over, it's reasonable to work towards neurolibre set up.

**Pull request closed without merging**
