### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ltetrel**
adding binder link

### CODE REVIEW

**Comment by htwangtw** [comment]
Okay this for what ever reason, didn't work. I am not sure if it's because of jupyter lab or dependency.
I am using binder link integrated with the book:
Screenshot from 2021-11-25 14-13-08
This works fine. 
I would prefer not to have a general binder link in the read me

**Comment by htwangtw** [comment]
Now that binder link doesn't build, I feel the last PR with data config broke it. I won't be too concerned as there's a lot of lecture based content

**Comment by ltetrel** [comment]
This was due to me creating a binder folder, https://github.com/main-educational/intro_ML/pull/6 should fix everything.

**Comment by ltetrel** [comment]
still, the fact that the jupyter lab depends on our requirement is really... weird... (the base environment without any requirements does not seem to handle that)

**Pull request closed without merging**
